name: Collect Data with Selenium

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - feature/*

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install all dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Configure and install Chrome
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      # Configure ChromeDriver
      - name: Set up ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          chromedriver --version

      # Run Python Script
      - name: Run Python scrape script
        env:
          club: ${{ secrets.club }}
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          email_sender: ${{ secrets.email_sender }}
          email_password: ${{ secrets.email_password }}
          email_reciever: ${{ secrets.email_reciever }}
          headless: True
          driver_path: '/usr/bin/chromedriver'
        run: |
          python main.py
