name: Collect Play Cricket Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * TUE'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'backend/**'
  push:
    branches:
      - main

concurrency:
  group: data-collection
  cancel-in-progress: false

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    name: Collect Data

    steps:

      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install all dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Python Script
      - name: Run Python data collection script
        env:
          club: ${{ secrets.club }}
          site_id: ${{ secrets.site_id }}
          api_token: ${{ secrets.api_token }}
          blob_connection_string: ${{ secrets.blob_connection_string }}
        run: |
          python -m backend.collect_data
